fix: import vitest is not needed to extend the module
The import is causing an issue as it is now making vitest a dependency of the module and results in error when running tests such as:
```
Error: Cannot find package 'vitest' imported from /path/to/project/ui/node_modules/.pnpm/@testing-library+jest-dom@6.6.3/node_modules/@testing-library/jest-dom/dist/vitest.mjs
```