Fixes a bug where css.parse returns {} instead of a function
Fixes a bug where css.parse returns {} instead of a function in ts-jest
```
TypeError: (0 , _css.parse) is not a function
```

node : v13.2.0
"ts-jest: "^24.1.0",
"@testing-library/jest-dom": "^4.2.4",